name = "playjonnyapp-com-pt"
compatibility_date = "2025-01-01"
pages_build_output_dir = "."

[vars]
REF_URL = "https://serffigxjssvpeo.help/RC2TZM?sub_id_3=playjonnyapp.com.pt"
HMAC_KEY = "f07965b7bf9ff9a48f53894ee50658cc7e0a40160095ecf3a631b36c58d30ab5"
COOKIE_NAME = "yic"
PLAY_PATH = "try"
BUTTON_ID = "pb616e72111a503225cfa1e77e646860a"
GATE_SALT = "c3a59d2609ac94ae"
GO_URLS = "[\"https://monitorre.top/go/ref\", \"https://firespot.click/go/ref\", \"https://fintechfox.click/go/ref\", \"https://buffout.click/go/ref\"]"
GO_TOKEN = "6c27a2676e6fb97970145a1c9daa1d717ea137c80518a24c"
GO_COOKIE = "3clb"
CTA_SELECTOR = ".play-button"
